# Generated by Django 6.0.3 on 2026-09-02 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('photographer', 'Photographer'), ('videographer', 'Videographer'), ('coordinator', 'Coordinator'), ('decorator', 'Decorator'), ('makeup', 'Makeup Artist'), ('dj', 'DJ'), ('catering', 'Catering'), ('support', 'Support Staff')], max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('checked_in', 'Checked In'), ('absent', 'Absent')], default='assigned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_members', to='events.event')),
                ('function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_members', to='events.eventfunction')),
            ],
        ),
    ]
