# Generated by Django 6.0.3 on 2026-09-02 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(choices=[('family', 'Family'), ('friends', 'Friends'), ('corporate', 'Corporate'), ('vip', 'VIP'), ('other', 'Other')], default='other', max_length=20)),
                ('side', models.CharField(choices=[('bride', 'Bride'), ('groom', 'Groom'), ('client', 'Client'), ('other', 'Other')], default='other', max_length=20)),
                ('invitation_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event')),
                ('function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='events.eventfunction')),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('number_of_guests', models.PositiveIntegerField(default=1)),
                ('meal_preference', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp', to='guests.guest')),
            ],
        ),
    ]
