# Generated by Django 6.0.3 on 2026-09-02 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorassignment',
            old_name='agreed_amount',
            new_name='assigned_price',
        ),
        migrations.RenameField(
            model_name='vendorassignment',
            old_name='assigned_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='available',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='vendorassignment',
            name='function',
        ),
        migrations.AddField(
            model_name='vendor',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('confirmed', 'Confirmed'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendorassignment',
            name='assigned_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorassignment',
            name='service_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendorassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('photography', 'Photography'), ('videography', 'Videography'), ('catering', 'Catering'), ('decoration', 'Decoration'), ('makeup', 'Makeup'), ('mehendi', 'Mehendi'), ('music', 'Music'), ('dj', 'DJ'), ('entertainment', 'Entertainment'), ('transportation', 'Transportation'), ('venue', 'Venue'), ('printing', 'Printing'), ('equipment', 'Event Equipment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vendorassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
